export type ImportedPerson = {
  category: 'Stanford' | 'Boğaziçi University' | 'Twitter' | 'Other';
  name: string;
  whyFlagged?: string;
  expertise?: string;
  startupExperienceNotes?: string;
  profileLink?: string;
  companyDescription?: string;
  durationMonths?: number | string;
  additionalInfoUrl?: string;
  capitalAccessScore?: number;
  lastContactDate?: string;
  sector?: string;
  contactNotes?: string;
};

export const importedPeople: ImportedPerson[] = [
  {
    category: 'Stanford',
    name: 'Vadim Axelrod',
    whyFlagged: 'Stanford MS in Computer Science · repeat CTO and AI founder',
    expertise: 'AI, computer vision, B2B revenue automation, product strategy',
    startupExperienceNotes:
      'CTO at a stealth startup; Co-Founder and Technical Advisor at EVE; Inception Studio alum',
    profileLink: 'https://www.linkedin.com/in/vadim1/',
    companyDescription:
      'Building computer-vision technology for aging support while advising EVE, an AI inbox revenue engine for SMBs.',
    durationMonths: 9,
    additionalInfoUrl: 'https://www.linkedin.com/in/vadim1/details/experience/',
    capitalAccessScore: 4,
    sector: 'AI & Computer Vision',
  },
  {
    category: 'Stanford',
    name: 'Joe Burg',
    whyFlagged: 'Stanford University',
    expertise:
      'PhD, Materials Science & Engineering (Stanford, Dauskardt Lab) — computational materials science researcher',
    startupExperienceNotes:
      'Currently "Principal" at a stealth-mode startup (founding team)',
    profileLink: 'https://www.linkedin.com/in/joe-burg/',
    companyDescription:
      'Come join us and build infrastructure for the intelligence era',
    durationMonths: 17,
    additionalInfoUrl: 'https://dauskardt.stanford.edu/people/joe-burg',
  },
  {
    category: 'Stanford',
    name: 'Yugendran Rajaendran',
    whyFlagged: 'Stanford University',
    expertise: 'Bioinformatics & Bioengineering',
    profileLink: 'https://www.linkedin.com/in/yugendran-rajaendran-2a6a961aa/',
    companyDescription:
      'Researcher at Stanford Center for Artificial Intelligence in Medicine and Imaging (AIMI); double major in CS + Bioengineering',
  },
  {
    category: 'Stanford',
    name: 'Kimball C',
    whyFlagged: 'Stanford University',
    expertise:
      'Employee at a stealth startup (Stanford, job title undisclosed)',
    profileLink: 'https://www.linkedin.com/in/chen8772/',
    companyDescription: 'Building sth interesting',
    durationMonths: 4,
    capitalAccessScore: 1,
    lastContactDate: '2026-05-04',
  },
  {
    category: 'Stanford',
    name: 'Alex Lerman',
    whyFlagged: 'Stanford University',
    expertise: 'Product Development, technical founder',
    profileLink: 'https://www.linkedin.com/in/alex-lerman-6060b732/',
    companyDescription: 'RYFT — Founder / Engineer (based in Mountain View)',
    durationMonths: 8,
  },
  {
    category: 'Stanford',
    name: 'Kelly Conlen',
    whyFlagged: 'Stanford University, Twitter',
    expertise:
      'Chief of Staff — strategy, operations, brand; transitioned from health/wellness consulting to founding her own venture',
    startupExperienceNotes:
      'Yes — Chief of Staff at a stealth-mode startup; previously founded her own health consulting business',
    profileLink: 'https://www.linkedin.com/in/kelly-conlen-08b418b4/',
    durationMonths: 20,
    capitalAccessScore: 1,
  },
  {
    category: 'Stanford',
    name: 'Vadim Axelrod',
    whyFlagged: 'Stanford University',
    expertise: 'technical fouder',
    companyDescription:
      'Revolutionizing aging support using computer vision - stay tuned!',
    durationMonths: 7,
    capitalAccessScore: 2,
    lastContactDate: '2026-10-07',
  },
  {
    category: 'Other',
    name: 'Cansu Saraçoğlu',
    whyFlagged: 'Founder History, VC History, University of Cambridge',
    expertise: 'Growth',
    profileLink: 'https://www.linkedin.com/in/cansusaracoglu/',
    durationMonths: 2,
    capitalAccessScore: 2,
    lastContactDate: '2026-10-09',
  },
  {
    category: 'Other',
    name: 'Niyati Joshi',
    whyFlagged: 'ex - Google, x - Pinteres , ',
    profileLink: 'https://www.linkedin.com/in/niyati-joshi-a47a481/',
    durationMonths: 12,
  },
  {
    category: 'Other',
    name: 'Barkha Sharma',
    whyFlagged: 'C - Level , Founder Hsitory',
    profileLink: 'https://www.linkedin.com/in/sharmabarkha/',
    companyDescription: 'Building Interview Intelligence',
    capitalAccessScore: 2,
  },
  {
    category: 'Other',
    name: 'Parker McKee',
    whyFlagged: 'University of Michigan, Investor',
    expertise: 'investment',
    profileLink: 'https://www.linkedin.com/in/parker-mckee-491118a7/',
    companyDescription: 'semantic layer for software',
    durationMonths: 3,
    capitalAccessScore: 2,
    lastContactDate: '2026-10-10',
  },
  {
    category: 'Other',
    name: 'I.Q. Sayed',
    whyFlagged:
      'Stanford, ex - Lyft, ex - Careem, ex -Facebook, Investor , Startup History, Advisor',
    expertise: 'Leadership, Technic Founder',
    profileLink: 'https://www.linkedin.com/in/iq-sayed/',
    durationMonths: 12,
    capitalAccessScore: 3,
    lastContactDate: '2026-10-08',
  },
  {
    category: 'Other',
    name: 'Prateek Jogani',
    whyFlagged: 'Founder History, Investor ,Technic Founder',
    expertise: 'Repeat entrepreneur',
    profileLink: 'https://www.linkedin.com/in/prateekjogani/',
    companyDescription: 'Builds teams and products',
    durationMonths: 7,
    capitalAccessScore: 3,
    lastContactDate: '2026-10-09',
  },
  {
    category: 'Other',
    name: 'Alessandro Rietmann',
    whyFlagged:
      'Founder History, Investor , ex Revolut, ,University of Cambridge\n\n',
    expertise: 'product, technic founder',
    profileLink: 'https://www.linkedin.com/in/alessandro-rietmann-21177152/',
    durationMonths: 6,
    capitalAccessScore: 2,
    lastContactDate: '2026-10-07',
  },
  {
    category: 'Other',
    name: 'Luke McCarthy',
    whyFlagged: ' Ex-Tripledot, Founder History',
    profileLink: 'https://www.linkedin.com/in/lukemccarthy1300/',
    companyDescription: 'Building what’s next in games ',
    durationMonths: 2,
    capitalAccessScore: 2,
    lastContactDate: '2026-10-06',
  },
  {
    category: 'Other',
    name: 'Andrew Poesaste',
    whyFlagged: 'Investor, VC History',
    expertise: 'investment',
    profileLink: 'https://www.linkedin.com/in/andrewpoesaste/',
    durationMonths: 10,
    capitalAccessScore: 3,
    lastContactDate: '2026-10-10',
  },
  {
    category: 'Other',
    name: 'Niko Ustin',
    whyFlagged: 'Stanford, Young, ',
    profileLink: 'https://www.linkedin.com/in/niko-ustin/',
    durationMonths: 19,
    capitalAccessScore: 1,
  },
  {
    category: 'Other',
    name: 'Aaron Misash',
    whyFlagged: 'Startup History',
    expertise: 'technic founder',
    profileLink: 'https://www.linkedin.com/in/aaron-misash-508295245/',
    companyDescription: 'Building Physical AI | Defense & Dual-Use',
    durationMonths: 1,
    capitalAccessScore: 2,
  },
  {
    category: 'Other',
    name: 'Ayush Kanodia',
    whyFlagged: 'ex - Google, Founder Histroy',
    expertise: 'technic founder',
    profileLink: 'https://www.linkedin.com/in/kanodiaayush/',
    companyDescription:
      'Using AI to build a delightful knowledge consumption experience',
    durationMonths: 17,
    capitalAccessScore: 2,
  },
  {
    category: 'Other',
    name: 'Jeremy Moffett',
    whyFlagged: 'Stanford, VC History, Startup History',
    expertise: 'Customer Success ',
    profileLink: 'https://www.linkedin.com/in/jeremy-moffett-9a9635102/',
    durationMonths: 4,
    capitalAccessScore: 1,
    lastContactDate: '2026-10-08',
  },
  {
    category: 'Other',
    name: 'Melis Kay',
    sector: 'Gaming',
  },
  {
    category: 'Other',
    name: 'Deniz Çolak',
    durationMonths: 12,
    capitalAccessScore: 4,
    lastContactDate: '2026-10-08',
  },
  {
    category: 'Other',
    name: 'Batuhan Mert Varilci ',
    whyFlagged: 'METU, Adjust , C - level',
    expertise: 'technic founder',
  },
  {
    category: 'Other',
    name: 'Yusufhan Kırçovalı',
    companyDescription: 'Seamflow',
  },
  {
    category: 'Other',
    name: 'Sipahi Demir',
    companyDescription: 'Verti',
    sector: 'Applied AI',
  },
  {
    category: 'Other',
    name: 'Camden Hulse',
    companyDescription: 'treena labs',
    contactNotes: 'X/Twitter',
  },
  {
    category: 'Other',
    name: 'Deepak gUPTA',
    whyFlagged: 'stanford',
    companyDescription: 'ROBOMYNE',
    contactNotes: 'X/Twitter',
  },
  {
    category: 'Other',
    name: 'Joaqim Venancio',
    whyFlagged: 'VC History , yc relationship , c - level ',
    expertise: 'product',
    companyDescription: 'Zenbild',
    sector: 'Building AI for construction',
  },
  {
    category: 'Other',
    name: 'Varun Vummadi',
    whyFlagged: 'YC',
    companyDescription: 'Giga',
    sector: 'Edtech',
  },
  {
    category: 'Other',
    name: 'Brooke Hopklins',
    whyFlagged: 'ex-Waymo , ex. -Google , NYU',
    companyDescription: 'Coval',
    durationMonths: 25,
  },
  {
    category: 'Other',
    name: 'Ege Demirkapı',
    companyDescription: 'Kaleon',
  },
  {
    category: 'Other',
    name: 'Efkan Turedi',
    whyFlagged: 'VC History, Startup History',
    companyDescription: 'komet',
    durationMonths: 1,
    capitalAccessScore: 2,
    lastContactDate: '2026-10-09',
    sector: 'Gaming',
  },
  {
    category: 'Other',
    name: 'Darijan Ducic',
    whyFlagged: 'Startup Hşstory, Lovable, Entrepreneur in Residence ',
    expertise: 'Community',
  },
  {
    category: 'Other',
    name: 'Jaka Bavdek',
    whyFlagged: 'Founder History',
  },
  {
    category: 'Other',
    name: 'Arish Shahab',
    whyFlagged: 'ex Harvard, Exit Histroy, Startup History',
    companyDescription: 'Amano',
  },
  {
    category: 'Other',
    name: 'Canaan Poh',
    whyFlagged: 'Startup History, ',
    expertise: 'gtm',
    companyDescription: 'lyhe.ai',
    durationMonths: 10,
  },
  {
    category: 'Other',
    name: 'Lyvia Chapman ',
    whyFlagged: 'Founders Inc',
    expertise: 'CMO , marketing',
    durationMonths: 7,
  },
  {
    category: 'Other',
    name: 'Stefano Delmanto',
    whyFlagged: 'ex - Palantir , ex - Stanford',
    expertise: 'technic founder',
    companyDescription: 'Oasis',
    durationMonths: 6,
  },
  {
    category: 'Other',
    name: 'Gabe Roeloffs',
    whyFlagged: 'ex- Aplle, Staj - Tesla , Staj - Microsoft',
    companyDescription: 'Zero Settle',
    sector: 'Building the İOS Revenue Platform',
    contactNotes: 'Missed opportunity',
  },
  {
    category: 'Other',
    name: 'Alex Teichman',
    whyFlagged: 'ex - Stanford, ex - Apple , Startup History',
    companyDescription: 'Happenstance',
    durationMonths: 32,
  },
  {
    category: 'Other',
    name: 'Elvin Atwine',
    whyFlagged: 'YC, Startup History',
    companyDescription: 'klo',
    durationMonths: 2,
    contactNotes: 'Rising star',
  },
  {
    category: 'Other',
    name: 'Can Atıkır',
    whyFlagged: 'Startup History, Techstars, NYU',
    expertise: 'technic founder',
    companyDescription: 'Highwatch',
    durationMonths: 11,
  },
  {
    category: 'Other',
    name: 'Oz Myerson',
    whyFlagged: 'Meta, ex - tripledots , Oxford',
    contactNotes: 'Possible future founder',
  },
  {
    category: 'Twitter',
    name: 'Vikram Subbiah',
    whyFlagged: 'ex -  SpaceX (Starlink), AWS, Tesla',
    expertise: 'technic founder',
    profileLink: 'https://x.com/tiovikram',
  },
  {
    category: 'Twitter',
    name: '?',
    whyFlagged: 'Vertical SaaS',
    expertise: 'Space × AI × climate ',
    profileLink: 'https://x.com/indrajit1',
    companyDescription:
      'Building atmospheric intelligence infrastructure from orbit. ',
  },
  {
    category: 'Twitter',
    name: 'Juan C. González T.',
    whyFlagged: 'Insurtech, LATAM',
    profileLink: 'https://x.com/JuanFiguro',
    additionalInfoUrl: 'https://www.figuro.la/',
  },
  {
    category: 'Twitter',
    name: 'Izgin Ozdas',
    whyFlagged: 'Physical AI • Robotics • Manufacturing',
    profileLink: 'https://x.com/izziebuilds',
  },
  {
    category: 'Twitter',
    name: 'Vatsal Aggarwal',
    whyFlagged: 'cambridge',
    expertise: 'built alexa’s first deep learning voice',
    profileLink: 'https://x.com/vatsal_aggarwal',
    additionalInfoUrl: 'https://metavoice.io/',
  },
  {
    category: 'Twitter',
    name: 'Thibaud MARTIN',
    whyFlagged: 'Former co-founder at @jubiweeapp (acq)',
    expertise: ' materials x AI ',
    profileLink: 'https://x.com/MARTINThibaud',
    additionalInfoUrl: 'https://www.altrove.ai/',
  },
  {
    category: 'Twitter',
    name: 'Ellery Buntel',
    whyFlagged: 'EF',
    expertise: 'Vertical SaaS',
    profileLink: 'https://x.com/ElleryBuntel',
    additionalInfoUrl: 'https://www.telepathic.ai/',
  },
  {
    category: 'Twitter',
    name: 'Chris Slater',
    profileLink: 'https://x.com/chris_sllater',
  },
  {
    category: 'Twitter',
    name: 'Khimani Fardeen',
    whyFlagged: ' Georgia Tech.',
    expertise: 'ML',
    profileLink: 'https://x.com/KhimaniFardeen',
    additionalInfoUrl: 'https://www.rounds.so/',
  },
  {
    category: 'Twitter',
    name: 'Mujtaba Syed',
    whyFlagged:
      'prev trading, ml, cs + math | @imctrading , @instagram , @Westernu',
    profileLink: 'https://x.com/Mutchtaba2',
    additionalInfoUrl: 'https://xynth.com/',
  },
  {
    category: 'Twitter',
    name: 'Sari Abu-Hamad',
    whyFlagged: 'Ex-IBM | UCLA CS',
    profileLink: 'https://x.com/sariabuhamad',
    additionalInfoUrl: 'https://probat.ai/',
  },
  {
    category: 'Twitter',
    name: 'Danny Chmaytelli',
    whyFlagged: 'CS @UCLA , Prev @Amazon @NASA',
    profileLink: 'https://x.com/DChmaytelli',
    additionalInfoUrl: 'https://tryradiant.ai/',
  },
  {
    category: 'Twitter',
    name: 'Aden Nurie',
    whyFlagged: '@solofounders @zfellows',
    profileLink: 'https://x.com/adennurie_',
    additionalInfoUrl: 'https://www.fastlease.ai/',
  },
  {
    category: 'Twitter',
    name: 'Mikul Saravanan',
    whyFlagged: 'Columbia University',
    expertise: 'AI & Robotics research ',
    profileLink: 'https://x.com/MikulSaravanan',
    additionalInfoUrl: 'https://wagoo.ai/',
  },
  {
    category: 'Twitter',
    name: 'Nick Linck',
    whyFlagged: 'prev: ai @ ibm research +  umich + zfellows, The residency',
    profileLink: 'https://x.com/nick_linck',
  },
  {
    category: 'Other',
    name: 'Refik Söylemez',
  },
  {
    category: 'Other',
    name: 'Thomas Panton',
  },
  {
    category: 'Other',
    name: 'Pietro Valente',
    companyDescription: 'Invertix',
    durationMonths: 1,
    sector: 'Energy',
  },
  {
    category: 'Other',
    name: 'Tuğçe Bulut',
    companyDescription: 'Eloquent Ai',
    sector: 'Finance',
  },
  {
    category: 'Other',
    name: 'Buğra Tosun',
    companyDescription: 'Munulus Tech',
  },
  {
    category: 'Other',
    name: 'Benedict Hofmann',
    companyDescription: 'opua',
  },
  {
    category: 'Other',
    name: 'Murat Can Kocakulak ',
    companyDescription: 'Kant Labs',
  },
  {
    category: 'Other',
    name: 'Mariah Ortiz',
    whyFlagged: 'Techstars',
    expertise: 'c - level , head;',
    companyDescription: 'Folklabs',
    durationMonths: 4,
    lastContactDate: '2026-10-07',
    sector: 'AI',
    contactNotes:
      '[Data anomaly: unexplained extra date in source (2026-10-08)]',
  },
  {
    category: 'Other',
    name: 'Marc Unger',
    whyFlagged: 'CEO, Advisor, Caltech, C - Level Positions ',
    expertise: 'Microfluidics , deep tech',
    profileLink: 'https://www.linkedin.com/in/marcaunger/',
    durationMonths: 5,
  },
  {
    category: 'Boğaziçi University',
    name: 'Emre Barut',
    whyFlagged: 'ex-Amazon, Boğaziçi University',
    expertise: 'Applied Science',
    profileLink: 'https://www.linkedin.com/in/emre-barut-468918a/',
    companyDescription: 'QKV Labs',
    durationMonths: 17,
  },
  {
    category: 'Boğaziçi University',
    name: 'Barış Özmen',
    whyFlagged: 'ex-Linkedin, ex-Meta , TUM, Boğaziçi University',
    expertise: 'Machine Learning',
    profileLink: 'https://www.linkedin.com/in/barisozmen/',
    durationMonths: 41,
    capitalAccessScore: 1,
  },
  {
    category: 'Boğaziçi University',
    name: 'Alp Kaymaz',
    whyFlagged: 'C-Level, Boğaziçi University',
    expertise: 'RD',
    profileLink: 'https://www.linkedin.com/in/alp-kaymaz-aaa65a8/',
    companyDescription: 'Coral Charge, ev charging ',
    durationMonths: 53,
  },
  {
    category: 'Boğaziçi University',
    name: 'Bulent Tastan',
    whyFlagged: 'ex META, ex AMZN, ex MSFT, UC Berkeley',
    expertise: 'blockchain ',
    profileLink: 'https://www.linkedin.com/in/bulenttastan/',
    companyDescription: 'Umi',
    capitalAccessScore: 2,
  },
  {
    category: 'Boğaziçi University',
    name: 'Omer Kucukdere',
    whyFlagged: 'Boğaziçi University',
    profileLink: 'https://www.linkedin.com/in/omercankucukdere/',
    durationMonths: 11,
    capitalAccessScore: 3,
    lastContactDate: '2026-05-02',
  },
  {
    category: 'Boğaziçi University',
    name: 'Nazli Tan',
    whyFlagged: 'Boğaziçi University, ODTU, ex - Getir',
    expertise: 'Growth',
    profileLink: 'https://www.linkedin.com/in/nazlitan/',
    durationMonths: 14,
    additionalInfoUrl: 'https://www.linkedin.com/company/hilbertsai/',
    capitalAccessScore: 1,
    lastContactDate: '2026-10-09',
  },
  {
    category: 'Boğaziçi University',
    name: 'Pinar Altin Yilmaz',
    whyFlagged: 'ex-aws, ',
    expertise: 'Sofware engineer, Machine Learning',
    profileLink: 'https://www.linkedin.com/in/pinar-altin-yilmaz/',
    durationMonths: 7,
  },
  {
    category: 'Boğaziçi University',
    name: 'Yagiz Kilic',
    whyFlagged: 'Founder History, NYU, Boğaziçi University',
    expertise: 'Partnership, Business Development',
    profileLink: 'https://www.linkedin.com/in/yagiz-kilic-507385b2/',
    durationMonths: 18,
    additionalInfoUrl: 'https://www.linkedin.com/company/chapter-foods/',
    capitalAccessScore: 3,
    sector: 'Foodtech',
  },
  {
    category: 'Boğaziçi University',
    name: 'Priya Surya',
    whyFlagged: 'Harvard Alum , YC Fellow, Harvard, Enterpreneur First',
    profileLink: 'https://www.linkedin.com/in/priyasurya/',
    durationMonths: 'Long term',
    additionalInfoUrl: 'https://www.linkedin.com/company/make-goodwill/',
    capitalAccessScore: 3,
    sector: 'Fintech',
  },
  {
    category: 'Boğaziçi University',
    name: 'Alp Yildirim',
    whyFlagged: 'Yale, Koç, ex- Trendyol, ex - QNB',
    expertise: 'Product Management',
    profileLink: 'https://www.linkedin.com/in/yildirimalp/',
    durationMonths: 11,
    contactNotes: 'yildirimlp@gmail.com',
  },
  {
    category: 'Boğaziçi University',
    name: 'Latife Genc',
    whyFlagged: 'ex-Meta, Carnegie Mellon University, Boğaziçi University',
    expertise: 'Machine Learning ',
    durationMonths: 25,
    sector: 'Edtech',
  },
  {
    category: 'Boğaziçi University',
    name: 'Umur Cubukcu',
    whyFlagged: 'Stanford, Boğaziçi University, YC, ex - Microsoft',
    profileLink: 'https://www.linkedin.com/in/umurc/',
    durationMonths: 33,
    additionalInfoUrl: 'https://www.linkedin.com/company/ubicloud/',
    capitalAccessScore: 1,
    lastContactDate: '2026-10-06',
    sector: 'Cloud',
  },
  {
    category: 'Boğaziçi University',
    name: 'Taner Ozcelik',
    whyFlagged: 'Boğaziçi University, The Wharton School , C - Level',
    expertise: 'EVP & GM',
    profileLink: 'https://www.linkedin.com/in/taner-ozcelik-3a790b8a/',
    durationMonths: 26,
    additionalInfoUrl: 'https://www.linkedin.com/company/mythic-ai/',
  },
  {
    category: 'Boğaziçi University',
    name: 'Onur Kuzucu',
    whyFlagged: 'Boğaziçi University',
    expertise: 'Product Management ',
    profileLink: 'https://www.linkedin.com/in/omer-kuzucu/',
    durationMonths: 30,
    capitalAccessScore: 1,
  },
  {
    category: 'Boğaziçi University',
    name: 'Deniz Ozgur',
    whyFlagged: 'Founder History, Forbes 30U30  , Boğaziçi University',
    profileLink: 'https://www.linkedin.com/in/denizozzgur/',
    additionalInfoUrl: 'https://www.linkedin.com/company/evercopy/',
    capitalAccessScore: 3,
    sector: 'Marketing',
  },
  {
    category: 'Boğaziçi University',
    name: 'Ataberk Sevim',
    whyFlagged: 'UC Berkeley, Boğaziçi University',
    expertise: 'technic founder',
    profileLink: 'https://www.linkedin.com/in/ataberksevim/',
    durationMonths: 32,
    capitalAccessScore: 1,
  },
  {
    category: 'Boğaziçi University',
    name: 'Tuğçe Seven',
    whyFlagged: 'Boğaziçi University, METU, ex- Zeo',
    expertise: 'business development',
    profileLink: 'https://www.linkedin.com/in/tugceseven/',
    durationMonths: 6,
    additionalInfoUrl: 'https://www.linkedin.com/company/parlioapp/',
    capitalAccessScore: 1,
  },
  {
    category: 'Boğaziçi University',
    name: 'Anil Kaya',
    whyFlagged: 'Georgia Institute of Technology, Boğaziçi University',
    expertise: 'product management ',
    profileLink: 'https://www.linkedin.com/in/anilkaya25/',
    capitalAccessScore: 2,
    lastContactDate: '2026-10-09',
    sector: 'Venture',
  },
  {
    category: 'Boğaziçi University',
    name: 'Ömer İncialan',
    whyFlagged: 'Boğaziçi University, Founder History',
    profileLink: 'https://www.linkedin.com/in/omerincialan/',
    durationMonths: 10,
    additionalInfoUrl: 'https://www.linkedin.com/company/boontext/',
    capitalAccessScore: 2,
    lastContactDate: '2026-10-09',
  },
  {
    category: 'Boğaziçi University',
    name: 'Nihat Gurmen',
    whyFlagged: 'Boğaziçi University, Universty of Michigan',
    expertise: 'technic founder',
    profileLink: 'https://www.linkedin.com/in/nihatgurmen/',
    durationMonths: 60,
    additionalInfoUrl: 'https://www.linkedin.com/company/chainbloq-labs-inc/',
  },
  {
    category: 'Boğaziçi University',
    name: 'Renan Cakirerk',
    whyFlagged: 'ex- Uber, Boğaziçi University , ',
    expertise: 'Staff Software Engineer ',
    profileLink: 'https://www.linkedin.com/in/bit2pixel/',
    durationMonths: 25,
    capitalAccessScore: 1,
    lastContactDate: '2026-10-06',
  },
  {
    category: 'Boğaziçi University',
    name: 'Sadriye Gorece',
    whyFlagged:
      'Robert Gordon University, Boğaziçi University, Fortune 40 Under 40, Founder History',
    profileLink: 'https://www.linkedin.com/in/sadriyegorece/',
    durationMonths: 15,
    additionalInfoUrl: 'https://www.linkedin.com/company/wowflow-ai/',
    capitalAccessScore: 3,
  },
  {
    category: 'Boğaziçi University',
    name: 'Berke Argın',
    whyFlagged: 'Boğaziçi University, EPFL, YC,  ex - UBS',
    profileLink: 'https://www.linkedin.com/in/arginberke/',
    durationMonths: 6,
    additionalInfoUrl: 'https://www.linkedin.com/company/compresr/',
    capitalAccessScore: 3,
    lastContactDate: '2026-10-07',
  },
  {
    category: 'Boğaziçi University',
    name: 'Ayşe Naz Erkan',
    whyFlagged: 'NYU, Boğaziçi University, ex - Twitter , ex - Robinhood',
    profileLink: 'https://www.linkedin.com/in/nazerkan/',
    durationMonths: 32,
    additionalInfoUrl: 'https://www.linkedin.com/company/lumiflowai/',
    capitalAccessScore: 2,
  },
  {
    category: 'Boğaziçi University',
    name: 'Aykut Girginer',
    whyFlagged: 'Boğaziçi University, ',
    expertise: 'machine learning',
    profileLink: 'https://www.linkedin.com/in/aykut-girginer-022a0918b/',
    durationMonths: 16,
    lastContactDate: '2026-10-07',
  },
  {
    category: 'Boğaziçi University',
    name: 'Onur Mergen',
    whyFlagged: 'Boğaziçi University, C - Level',
    expertise: 'technic founder',
    profileLink: 'https://www.linkedin.com/in/omergen/',
    durationMonths: 17,
    additionalInfoUrl: 'https://www.linkedin.com/company/ezcater/',
  },
  {
    category: 'Boğaziçi University',
    name: 'Baran Ataş',
    whyFlagged: 'Boğaziçi University, Startup History',
    profileLink: 'https://www.linkedin.com/in/baranatas/',
    durationMonths: 6,
    additionalInfoUrl: 'https://www.linkedin.com/company/gettalp/',
    capitalAccessScore: 1,
    sector: 'We create AI personas to simulate human intent.',
  },
  {
    category: 'Boğaziçi University',
    name: 'İsmet Öker',
    whyFlagged:
      'Boğaziçi University, Bilkent, ex - Getir, ex - Huawei, C - Level',
    expertise: 'technic founder',
    profileLink: 'https://www.linkedin.com/in/ismet-oker/',
    durationMonths: 10,
    additionalInfoUrl: 'https://www.linkedin.com/company/thisispai/',
    capitalAccessScore: 1,
    sector: 'the agentic AI teammate for B2C growth',
  },
  {
    category: 'Boğaziçi University',
    name: 'Sina Atalay',
    whyFlagged: 'Boğaziçi University, Princeton University',
    expertise: 'technic founder',
    profileLink: 'https://www.linkedin.com/in/sinaatalay/',
    durationMonths: 14,
    additionalInfoUrl: 'https://www.linkedin.com/company/academa/',
    sector:
      'Our mission is to produce computer-animated video lectures for every STEM course, in multiple languages.',
  },
  {
    category: 'Boğaziçi University',
    name: 'Halis Osman Erkan',
    whyFlagged: 'Boğaziçi University, ex- Kron , ex - Nokia C - Level',
    profileLink: 'https://www.linkedin.com/in/halisosmanerkan/',
    additionalInfoUrl: 'https://www.linkedin.com/company/defensxy/',
    sector: 'Redefining Your Browser as a Secure Digital Workspace',
    contactNotes: 'Scaleup',
  },
  {
    category: 'Boğaziçi University',
    name: 'Esat Canli',
  },
];

const categoryAliases: Record<string, ImportedPerson['category']> = {
  stanford: 'Stanford',
  'global-tier-1': 'Stanford',
  'top-university': 'Stanford',
  'bogazici-university': 'Boğaziçi University',
  'regional-tier-1': 'Boğaziçi University',
  twitter: 'Twitter',
  'faang-big-tech': 'Twitter',
  other: 'Other',
};

const keywordGroups: Record<string, string[]> = {
  'fintech-alumni': [
    'fintech',
    'finance',
    'revolut',
    'ramp',
    'qnb',
    'robinhood',
  ],
  'ai-alumni': [' ai', 'machine learning', ' ml', 'deep learning', 'research'],
  'saas-alumni': ['saas', 'software', 'product'],
  'top-consulting': ['consulting', 'strategy', 'chief of staff'],
  'technical-tier-1': [
    'stanford',
    'caltech',
    'epfl',
    'georgia tech',
    'carnegie mellon',
  ],
  'stem-focus': [
    'engineering',
    'science',
    'research',
    'machine learning',
    'robotics',
  ],
  'top-mba': ['wharton', 'harvard', 'business'],
  'serial-founder': [
    'founder history',
    'startup history',
    '2nd-time',
    'repeat entrepreneur',
  ],
  'prior-exit': ['exit', 'acq', 'acquisition'],
  'failed-founder': ['missed opportunity'],
  'accelerator-alumni': [
    'yc',
    'techstars',
    'entrepreneur first',
    ' ef',
    'founders inc',
  ],
  'active-angel-investor': ['investor', 'investment'],
  'startup-advisor': ['advisor', 'entrepreneur in residence'],
  'ai-ml-infrastructure': [
    'ai',
    'machine learning',
    ' ml',
    'deep learning',
    'applied ai',
  ],
  'fintech-payments': [
    'fintech',
    'finance',
    'payments',
    'accounting',
    'qnb',
    'robinhood',
  ],
  'b2b-saas': ['saas', 'enterprise', 'software', 'procurement'],
  'deep-tech': [
    'deep tech',
    'materials',
    'robotics',
    'physical ai',
    'space',
    'satellite',
    'microfluidics',
  ],
  'climate-greentech': ['climate', 'energy', 'ev charging'],
  'healthtech-biotech': [
    'health',
    'bioinformatics',
    'bioengineering',
    'clinical',
    'aging',
  ],
  'defense-govtech': ['defense', 'dual-use', 'secure digital workspace'],
  'consumer-creator': ['consumer', 'gaming', 'games', 'marketing'],
  'hr-future-work': ['hr', 'interview', 'workplace', 'future work'],
  turkey: ['boğaziçi', 'metu', 'odtu', 'koç', 'turkey', 'getir', 'trendyol'],
  mena: ['careem', 'mena', 'latam'],
  nordics: ['nordic'],
  dach: ['germany', 'austria', 'switzerland'],
  iberia: ['spain', 'portugal'],
  london: ['london', 'cambridge', 'oxford'],
  'new-york-san-francisco': ['nyu', 'stanford', 'berkeley', 'mountain view'],
};

export function peopleForProject(categoryId: string) {
  const directCategory = categoryAliases[categoryId];
  if (directCategory) {
    const matches = importedPeople.filter(
      (person) => person.category === directCategory,
    );

    if (categoryId === 'faang-big-tech') {
      return matches.sort((a, b) => {
        if (a.name === 'Danny Chmaytelli') return -1;
        if (b.name === 'Danny Chmaytelli') return 1;
        return 0;
      });
    }

    return matches;
  }

  const keywords = keywordGroups[categoryId];
  if (!keywords)
    return importedPeople.filter((person) => person.category === 'Other');

  return importedPeople.filter((person) => {
    const searchable = [
      person.whyFlagged,
      person.expertise,
      person.startupExperienceNotes,
      person.companyDescription,
      person.sector,
      person.contactNotes,
    ]
      .filter(Boolean)
      .join(' ')
      .toLocaleLowerCase('en-US');
    return keywords.some((keyword) => searchable.includes(keyword));
  });
}
