'use client';
import * as React from 'react';
import { useWorkspace } from '@/contexts/organization-context';
import { requestJson } from '@/lib/request-json';
import { createOnboardingOrganization } from '@/lib/onboarding-client';
import { questionOptions,multiQuestion,validateAnswer,type OnboardingQuestion } from '@/lib/onboarding-model';
import * as Button from '@/components/ui/button';
import { ChoiceGroup } from './question-choice';
import { DashedDivider } from '@/components/dashed-divider';
export default function DatabaseOnboarding(){
 const {loading,membership,refresh}=useWorkspace();const [questions,setQuestions]=React.useState<OnboardingQuestion[]>([]);const [answers,setAnswers]=React.useState<Record<string,string|string[]>>({});const [name,setName]=React.useState('');const [step,setStep]=React.useState(0);const [ready,setReady]=React.useState(false);const [pending,setPending]=React.useState(false);const [error,setError]=React.useState('');const [completed,setCompleted]=React.useState(false);const created=React.useRef(false);const inFlight=React.useRef(false);
 React.useEffect(()=>{let cancelled=false;requestJson('/api/onboarding').then(data=>{if(cancelled)return;const qs=data.questions as OnboardingQuestion[];setQuestions(qs);const initial:Record<string,string|string[]>={};for(const answer of data.answers){const question=qs.find(q=>q.id===answer.question_id);if(question)initial[question.question_key]=answer.answer_value;}setAnswers(initial);const sections=Array.from(new Set(qs.map(q=>q.section_key)));const first=sections.findIndex(key=>qs.filter(q=>q.section_key===key).some(q=>!validateAnswer(q,initial[q.question_key])));setStep(first<0?Math.max(0,sections.length-1):first);setCompleted(data.state?.status==='completed');setReady(true);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[]);
 React.useEffect(()=>{if(membership?.organization?.name)setName(membership.organization.name);},[membership]);
 const sections=Array.from(new Set(questions.map(q=>q.section_key)));const visible=questions.filter(q=>q.section_key===sections[step]);
 async function save(e:React.FormEvent){e.preventDefault();if(inFlight.current)return;inFlight.current=true;setPending(true);setError('');try{
 if(!membership&&!created.current){await createOnboardingOrganization(name.trim());created.current=true;await refresh();}
 const final=step===sections.length-1;const values=Object.fromEntries(visible.map(q=>[q.question_key,answers[q.question_key]??'']));await requestJson('/api/onboarding',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sectionKey:sections[step],answers:values,completed:final})});if(final)setCompleted(true);else setStep(step+1);
 }catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{inFlight.current=false;setPending(false);}}
 if(!ready||loading)return <div className='p-8'>{error?<p role='alert'>{error}<button className='ml-3 underline' onClick={()=>window.location.reload()}>Retry</button></p>:<p role='status'>Loading onboarding…</p>}</div>;
 if(!questions.length)return <div className='p-8' role='alert'>No active onboarding questions are configured.</div>;
 return <div className='flex min-h-screen flex-col bg-bg-white-0 lg:flex-row'><aside className='hidden w-[262px] shrink-0 flex-col gap-12 px-9 py-10 lg:flex'><img src='/images/brand/scouter-mark.webp' alt='Scouter' className='size-10'/>{sections.map((key,index)=><button disabled={pending||index>step} onClick={()=>{setStep(index);setCompleted(false);}} className={'text-left text-label-md '+(index===step?'text-orange-500':'text-text-sub-600')} key={key}>Step {index+1}/{sections.length}<br/>{questions.find(q=>q.section_key===key)?.section_title}</button>)}</aside>
 <div className='flex flex-1 flex-col md:grid md:grid-cols-[minmax(0,550px)_minmax(0,1fr)]'><div className='flex flex-col justify-center rounded-2xl bg-bg-weak-50 p-8 md:m-2'><h2 className='text-title-h6'>{name||'Your organization'}</h2><div className='mt-6 space-y-4'>{questions.filter(q=>answers[q.question_key]?.length).map(q=><div key={q.id}><p className='text-label-xs text-text-soft-400'>{q.question}</p><p className='mt-1 text-label-sm'>{(Array.isArray(answers[q.question_key])?answers[q.question_key] as string[]:[answers[q.question_key] as string]).map(value=>questionOptions(q).find(o=>o.value===value)?.label||value).join(', ')}</p></div>)}</div></div>
 <form onSubmit={save} className='mx-auto flex w-full max-w-[700px] flex-col justify-center gap-7 p-6 lg:p-12'><h1 className='text-title-h4'>{completed?'Onboarding complete':visible[0]?.section_title}</h1><DashedDivider/>{completed?<><p>Your organization profile has been saved.</p><Button.Root asChild><a href='/auth/continue'>Continue to workspace</a></Button.Root></>:<>
 {step===0&&<label className='space-y-2 text-label-md'>Organization name<input required maxLength={100} disabled={!!membership||created.current} value={name} onChange={e=>setName(e.target.value)} className='block h-10 w-full rounded-10 border border-stroke-soft-200 bg-bg-white-0 px-3'/></label>}
 {visible.map(q=><div key={q.id} className='space-y-3'><label htmlFor={q.id} className='block border-l-2 border-orange-500 pl-3 text-label-md'>{q.question}{q.is_required?' *':''}</label>{questionOptions(q).length?<ChoiceGroup options={questionOptions(q)} {...(multiQuestion(q)?{values:(answers[q.question_key]||[]) as string[],onToggle:(value:string)=>setAnswers(current=>{const selected=(current[q.question_key]||[]) as string[];return {...current,[q.question_key]:selected.includes(value)?selected.filter(v=>v!==value):[...selected,value]};})}:{value:(answers[q.question_key]||'') as string,onSelect:(value:string)=>setAnswers(current=>({...current,[q.question_key]:value}))})}/>:<input id={q.id} type={['url','email','number'].includes(q.input_type)?q.input_type:'text'} required={q.is_required} value={(answers[q.question_key]||'') as string} onChange={e=>setAnswers(current=>({...current,[q.question_key]:e.target.value}))} maxLength={10000} className='h-10 w-full rounded-10 border border-stroke-soft-200 bg-bg-white-0 px-3'/>}</div>)}
 <div className='flex gap-3'>{step>0&&<Button.Root type='button' disabled={pending} onClick={()=>setStep(step-1)}>Back</Button.Root>}<Button.Root className='flex-1' type='submit' disabled={pending||!name.trim()||visible.some(q=>!validateAnswer(q,answers[q.question_key]))}>{pending?'Saving…':step===sections.length-1?'Finish':'Continue'}</Button.Root></div></>}{error&&<p role='alert' className='text-error-base'>{error}</p>}</form></div></div>;
}
